# ==============================================================================
# PROJECT METADATA
# ==============================================================================

name: vixen

description: "Vixen Telegram Bot"

publish_to: "none"

version: 0.5.5

homepage: https://plugfox.dev

repository: https://github.com/plugfox/vixen

issue_tracker: https://github.com/plugfox/vixen/issues

#funding:
#  - https://www.buymeacoffee.com/
#  - https://www.patreon.com/
#  - https://boosty.to/

#topics:
#  -
#  -

#platforms:
#  linux:
#  macos:
#  windows:

#screenshots:
#  - description: 'Screenshot 1'
#    path: screenshot_1.png

# ==============================================================================
# PROJECT STRUCTURE
# ==============================================================================

executables:
  - bin/vixen.dart

# ==============================================================================
# DEPENDENCIES
# ==============================================================================

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  # Annotation
  #json_annotation: ^4.9.0
  meta: ^1.16.0

  # Utility
  args: ^2.6.0
  collection: ^1.19.1
  path: ^1.9.1
  async: ^2.13.0
  convert: ^3.1.2
  intl: ^0.20.2
  stack_trace: ^1.12.1
  # yaml: ^3.1.3 # Allow to use yaml configuration

  # Hash function
  xxh3: ^1.2.0

  # Image processing (for captcha)
  image: ^4.5.3

  # Logger
  l: ^5.0.0

  # Database (SQLite)
  drift: ^2.25.1

  # Network
  http: ^1.2.2

  # Server
  shelf: ^1.4.2
  shelf_router: ^1.1.4

dev_dependencies:
  # Linting
  lints: ^5.1.1

  # Testing
  test: any

  # Code generation
  build_runner: ^2.4.15
  drift_dev: ^2.25.2
  pubspec_generator: ^4.1.0-pre.1
  #json_serializable: ^6.8.0
